name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build
        run: mvn clean compile
      - name: Test
        run: mvn clean test
      - name: Create Docker Latest
        run: mvn -Djib.to.image=$DOCKER_IMAGE_NAME -Dmaven.test.skip=true clean install jib:build